apiVersion: 1

datasources:
  - name: Trino
    type: trino-datasource
    access: proxy
    url: http://trino:8080
    jsonData:
      catalog: hive
      schema: smartgrid
    isDefault: true
    editable: true
